### PR TITLE
maint: add CI jobs to build and test a Windows wheel

### LINKED ISSUE #10: Windows support
I ran the test suite and for each python version, the error is different.
python 3.6
```
>python test/test.py 
test_fmpz...
```

python 3.7
```
>python test/test.py 
Traceback (most recent call last):
  File "test/test.py", line 439, in <module>
    sys.stdout.write("test_fmpz..."); test_fmpz(); print("OK")
  File "test/test.py", line 19, in test_fmpz
    assert flint.fmpz() == flint.fmpz(0)
AssertionError
```

python 3.8
```
>python test/test.py 
Traceback (most recent call last):
  File "test/test.py", line 439, in <module>
    sys.stdout.write("test_fmpz..."); test_fmpz(); print("OK")
  File "test/test.py", line 26, in test_fmpz
    assert ltype(s) + rtype(t) == s + t
AssertionError
```

One possible issue could be that, `long` is used everywhere instead of `long long`. For example, `PyLong_AsLongLongAndOverflow` should be used instead of `PyLong_AsLongAndOverflow` at https://github.com/fredrik-johansson/python-flint/blob/master/src/fmpz.pyx#L4.

### PR DESCRIPTION
**Pull request by oscarbenjamin**
This adds a script to build a wheel on Windows amd64 using mingw-w64 under msys2 based on the recipe discussed in #1. Another CI job will test the installed wheel.

The resulting wheel is broken because of at least #10 if not other problems as well. With this though it should at least in principle be possible to see in CI whether or not the module works on Windows.

I haven't integrated this with the other build scripts yet although mostly this leverages the existing `bin/build_dependencies_unix.sh` script. Currently this changes `setup.py` which it probably shouldn't so I should come up with a better solution for that before this is merged (presumably someone is depending on that Windows specific code in the setup.py). I don't think it's worth trying to integrate building Windows wheels with the other cibuildwheel setup until at least it is possible to build a working wheel on Windows.

Both setup.py, distutils and numpy.distutils are deprecated and numpy.distutils will apparently be removed in Python 3.12. A better fix for the build system would be to use `build` as a frontend:
https://pypa-build.readthedocs.io/en/latest/
Then the backend would be something like meson-python or cmake I guess:
https://labs.quansight.org/blog/2021/07/moving-scipy-to-meson
If eventually a future build system will be used it's probably better to leave setup.py alone so that it can continue to work for anyone who is still using it.

Once I've reverted the changes to setup.py I suggest:

1. Merge this so that Windows is tested in CI.
2. Fix #10 and any other issues until there is a working Windows wheel in CI.
3. Make it so that CI can produce a suite of wheels and integrate the Windows wheels into the cibuildwheel setup.
4. Only think about future build systems at the point where CI can at least build and test wheels for the major platforms so that any changes are testable.

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
I've rebased this on top of #28

File: bin/build_mingw64_wheel.sh [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+source .local/venv/Scripts/activate
+pip install numpy cython wheel delvewheel
+
+# Build the wheel
+C_INCLUDE_PATH=.local/include/ LIBRARY_PATH=.local/lib/ python setup.py build_ext -cmingw32 -f bdist_wheel
+
+# Make the wheel relocatable
+delvewheel repair dist/python_flint-0.3.0-cp310-cp310-win_amd64.whl \
+        --add-path .local/bin:.local/lib/ \
+        '--no-mangle=libflint-17.dll;libarb-2.dll;libgmp-10.dll;libmpfr-6.dll;libgcc_s_seh-1.dll'
```
Comment (isuruf) [inline bin/build_mingw64_wheel.sh:77]: Not mangling common DLLs like `libgcc_s_seh-1.dll` is going to cause conflicts with other libraries using the same DLL.

File: setup.py [hunk 2]
```diff
@@ -9,7 +9,7 @@
 from distutils.sysconfig import get_config_vars
 
 if sys.platform == 'win32':
-    libraries = ["arb", "flint", "mpir", "mpfr", "pthreads"]
+    libraries = ["arb", "flint", "mpfr", "gmp"]
```
[the remark this answers is not in the document]
Comment (oscarbenjamin) [reply setup.py:12]: I think I'll peg this to an environment variable for now. Longer term I think we want a build system that doesn't use setup.py or distutils at all and that probably means that exactly how it would be configured would be quite different.

**Comment by oscarbenjamin** [comment]
So the Windows job runs fine, builds a wheel and then passes all tests.

The failing tests are 32 bit Linux and I think are some other problem with the CI arrangement maybe.

File: bin/build_mingw64_wheel.sh (hunk 1 above)
Comment (oscarbenjamin) [reply bin/build_mingw64_wheel.sh:77]: Looks like scipy just unpacks the wheel and runs strip on all DLLs:
https://github.com/scipy/scipy/blob/502df0ece7eb9525de8a7f243044b3fe18ad5cca/tools/wheels/repair_windows.sh#L14-L20

Comment (oscarbenjamin) [reply bin/build_mingw64_wheel.sh]: I've used `strip` and removed the `--no-mangle` argument here and it seems to work.

**Comment by oscarbenjamin** [comment]
Okay, that was a long slog!

With this PR we now have Windows wheels built and tested in CI along with Linux and OSX wheels. I knew it would be hard to get Windows working which is why I've put this off for almost two years. It's working now in CI and I've also tested downloading the wheels and using them locally. Hopefully that means that no one needs to actually use Windows directly any more!

The most significant remaining item is OSX on ARM but that's much less of an issue than Windows 64-bit.

I'm going to merge this now and then do two things:

1. Take a look at making OSX universal2 wheels. If it's not hard then add those.
2. Increase test coverage for existing features (#29).

After those are done I think it's time for a new release of python-flint with binary wheels on PyPI.

**Comment by fredrik-johansson** [comment]
That's awesome! Thanks!
